### ISSUE TITLE
Add'l docs - Asterisk version support, FreePBX instructions, etc?

### ISSUE THREAD

**Issue by sudofox** [npstn-soft/ProjectMF2.0#2]
Hiya, trying to get started with this but, having never used Asterisk before, I am a bit lost as to what versions are supported and so on. As a fledgeling hobbyist, it would be helpful to have a little more info in the README as to what version of Asterisk I should try setting things up on and so on.

My eventual goal is to have in-band MF signaling on an Asterisk server that is connected to NPSTN as well as the regular PSTN through my telephone line.

**Comment by npstn-soft** [comment]
Hello,

The NPSTN project has merged with TandMX (If you go to the webpage you will see it now redirects)

For additional support on joining TandMX and on utilizing MF using this script you can contact Jaiden Borich at hismartalarms@gmail.com or add him on Discord NotifierGuy1369#9110

Thanks for reaching out!

**Comment by sudofox** [comment]
I appreciate that information. Though, in closing the GitHub issue, are you saying this project is discontinued or...?

I was looking at it specifically because Project MF (the original) requires very old software versions and that didn't sound like a very fun idea to work with.

**Comment by npstn-soft** [comment]
This script is compatible with the latest versions of Asterisk. I currently use this on Asterisk 18

When this script was created there was no native way of doing MF Signaling in Asterisk (using any channel technology you want, e.g SIP), however as of one of the newer releases there is a built-in channel agnostic receiver and sender. I still prefer to use this utility however as I feel it is a bit more flexible and modifiable.
